# dataconnect/example/mutations.gql

mutation CreateCategory($name: String!, $orderIndex: Int!, $imageUrl: String) @auth(level: NO_ACCESS) {
  category_insert(data: { name: $name, orderIndex: $orderIndex, imageUrl: $imageUrl })
}

mutation CreateProduct($categoryId: UUID!, $name: String!, $description: String!, $price: Float!) @auth(level: NO_ACCESS) {
  product_insert(data: { categoryId: $categoryId, name: $name, description: $description, price: $price })
}
mutation CreateOrder($id: UUID!, $total: Float!, $status: String!) @auth(level: NO_ACCESS) {
  order_insert(data: { id: $id, total: $total, status: $status })
}

mutation CreateOrderItem($orderId: UUID!, $productName: String!, $quantity: Int!) @auth(level: NO_ACCESS) {
  orderItem_insert(data: { orderId: $orderId, productName: $productName, quantity: $quantity })
}
mutation CreateUser($email: String!, $passwordHash: String!, $name: String!) @auth(level: NO_ACCESS) {
  user_insert(data: { email: $email, passwordHash: $passwordHash, name: $name })
}