
query GetCategories @auth(level: PUBLIC) {
  categories(orderBy: [{ orderIndex: ASC }]) {
    id
    name
    imageUrl
    orderIndex
  }
}

query GetProductsByCategory($categoryId: UUID!) @auth(level: PUBLIC) {
  products(where: { categoryId: { eq: $categoryId } }) {
    id
    name
    description
    price
    imageUrl
    isAvailable
  }
}

query GetOrders @auth(level: PUBLIC) {
  orders(orderBy: [{ createdAt: DESC }]) {
    id
    total
    status
    createdAt
  }
}
query GetUserByEmail($email: String!) @auth(level: NO_ACCESS) {
  users(where: { email: { eq: $email } }) {
    id
    email
    passwordHash
    name
  }
}