extend type OrderItem {
  """
  ✨ Implicit foreign key field based on `OrderItem`.`order`. It must match the value of `Order`.`id`. See `@ref` for how to customize it.
  """
  orderId: UUID! @fdc_generated(from: "OrderItem.order", purpose: IMPLICIT_REF_FIELD)
}
extend type Product {
  """
  ✨ Implicit foreign key field based on `Product`.`category`. It must match the value of `Category`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID! @fdc_generated(from: "Product.category", purpose: IMPLICIT_REF_FIELD)
}
